name: alaram
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  intl: ^0.18.1
  provider:
  shared_preferences: ^2.2.2
  timestamp_to_string: ^0.0.1
  flutter_local_notifications: ^17.2.3
  timezone: ^0.9.0
  another_flushbar: ^1.12.30
dependency_overrides:
  win32: ^5.5.4


flutter:


  uses-material-design: true


