name: alaram
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  google_fonts: ^6.2.1
  flutter_screenutil: ^5.6.0
  get: ^4.6.6
  video_player: ^2.9.2
  shared_preferences: ^2.3.2
  hive_flutter: ^1.1.0
  animated_notch_bottom_bar: ^1.0.3
  syncfusion_flutter_calendar: ^27.1.55
  fl_chart: ^0.69.0
  printing: ^5.13.3
  pdf: ^3.11.1
  share_plus: ^10.1.1
  path_provider: ^2.1.4
  intl: ^0.19.0
  animated_text_kit: ^4.2.2
  table_calendar: ^3.1.2
  delightful_toast: ^1.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.13
  flutter_local_notifications: ^17.2.3
  timezone: ^0.9.0
  another_flushbar: ^1.12.30
dependency_overrides:
  win32: ^5.5.4


flutter:


  uses-material-design: true


  assets:
    - assets/logo/
    - assets/logo/index-logo.jpg
    - assets/profile/avatar.jpg